# Generated by Django 3.2.5 on 2022-10-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0002_auto_20221026_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usedcars',
            options={'verbose_name_plural': 'Used Cars'},
        ),
    ]
