# Generated by Django 3.2.5 on 2022-10-27 11:50

import apps.shared.utils.valid_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0004_auto_20221027_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='car/video', validators=[apps.shared.utils.valid_size.validate_file_size]),
        ),
        migrations.AddField(
            model_name='usedcars',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='car/usedcars', validators=[apps.shared.utils.valid_size.validate_img_size]),
        ),
        migrations.AddField(
            model_name='usedcars',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='car/usedcars', validators=[apps.shared.utils.valid_size.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='car',
            name='external_photo',
            field=models.ImageField(upload_to='car/external_pics', validators=[apps.shared.utils.valid_size.validate_img_size]),
        ),
        migrations.AlterField(
            model_name='car',
            name='internal_photo',
            field=models.ImageField(upload_to='car/indernal_pics', validators=[apps.shared.utils.valid_size.validate_img_size]),
        ),
        migrations.AlterField(
            model_name='car',
            name='side_photo',
            field=models.ImageField(upload_to='car/side_pics', validators=[apps.shared.utils.valid_size.validate_img_size]),
        ),
    ]
