# Generated by Django 3.2.5 on 2022-10-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0005_auto_20221027_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcompany',
            name='logo',
            field=models.ImageField(upload_to='car/company_logo'),
        ),
    ]
