from apps.automobile.serializers.car import CarModelSerializer, CarlikeSerializer
from apps.automobile.serializers.positions_category import PositionCategorySerializer, ComparePositionSerializer
from apps.automobile.serializers.company import CompanySerializer
from apps.automobile.serializers.gifts import BonusSerializer
from apps.automobile.serializers.usedcars import UsedCarsSerializer
