from apps.automobile.serializers.car import CarModelSerializer
from apps.automobile.serializers.positions_category import PositionCategorySerializer, ComparePositionSerializer
from apps.automobile.serializers.company import CompanySerializer
from apps.automobile.serializers.gifts import BonusSerializer
