# Generated by Django 3.2.5 on 2022-10-24 11:11

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pic',
            field=models.ImageField(null=True, upload_to='comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='videoUrl',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
