# Generated by Django 3.2.5 on 2022-10-24 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '998 [XX] [XXX XX XX]'. Up to 17 digits allowed.", regex='^(\\+7|7|8), ^998[0-9]{9}$')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
