# Generated by Django 3.2.5 on 2022-10-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='theme',
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('uz', 'Uzbek'), ('ru', 'Russian')], max_length=25, null=True),
        ),
    ]
