# Generated by Django 3.2.5 on 2022-10-23 13:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='AboutUs')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='AboutUs')),
                ('employees', models.IntegerField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('start_time', models.TimeField(default='10:00')),
                ('end_time', models.TimeField(default='18:00')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '998 [XX] [XXX XX XX]'. Up to 17 digits allowed.", regex='^(\\+7|7|8), ^998[0-9]{9}$')])),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, help_text='Display this banner on the website.')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='banners/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Filials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='filials')),
                ('video', models.FileField(blank=True, null=True, upload_to='filials')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=18, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '998 [XX] [XXX XX XX]'. Up to 17 digits allowed.", regex='^(\\+7|7|8), ^998[0-9]{9}$')])),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.address')),
            ],
            options={
                'verbose_name_plural': 'Our Filials',
            },
        ),
    ]
