# Generated by Django 3.2.5 on 2022-10-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_partners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
