# Generated by Django 3.2.5 on 2022-10-27 11:50

import apps.shared.utils.valid_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_delete_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='AboutUs', validators=[apps.shared.utils.valid_size.validate_img_size]),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='AboutUs', validators=[apps.shared.utils.valid_size.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='filials',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='filials', validators=[apps.shared.utils.valid_size.validate_img_size]),
        ),
        migrations.AlterField(
            model_name='filials',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='filials', validators=[apps.shared.utils.valid_size.validate_file_size]),
        ),
    ]
