# Generated by Django 3.2.5 on 2022-10-27 22:26

import apps.shared.utils.valid_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20221027_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='company/AboutUs', validators=[apps.shared.utils.valid_size.validate_img_size]),
        ),
        migrations.AlterField(
            model_name='aboutcompany',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='company/AboutUs', validators=[apps.shared.utils.valid_size.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='partners',
            name='logo',
            field=models.ImageField(upload_to='company/parters'),
        ),
    ]
