# Generated by Django 3.2.5 on 2022-10-27 22:26

import apps.shared.utils.valid_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='created',
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='siteconfig/banners/', validators=[apps.shared.utils.valid_size.validate_img_size]),
        ),
    ]
